seung-lab/cloud-files

automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/connectionpools.py, cloudfiles/interfaces.py, cloudfiles/paths.py
Enables memory based operations.
=> feat: adds mem:// protocol

ChangeLog, automated_test.py, cloudfiles/compression.py, cloudfiles/interfaces.py, requirements.txt
There is a potential performance impact to uncompressed datasets for `file://` protocol for every new compression protocol we add.
=> feat: adds zstd as a supported compressor

README.md, automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/interfaces.py, cloudfiles/lib.py
```python
cf.size([ files... ])
>> { fname: size_in_bytes }
```
=> feat(size): get byte sizes of files

.travis.yml, requirements.txt, setup.cfg, setup.py
Fixes https://github.com/seung-lab/cloud-volume/issues/385
=> fix: bump google-crc32c to a fixed version

automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/interfaces.py, cloudfiles/paths.py
Also trying to add support for custom s3 endpoints like so:
s3://https://..../bucket/....
=> feat: simplifying the paths engine to support e.g. gs://bucket datasets

automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/compression.py, cloudfiles/connectionpools.py, cloudfiles/interfaces.py, cloudfiles/paths.py, cloudfiles/threaded_queue.py, requirements.txt
feat(to_https_protocol): accepts ExtractedPath as argument
=> fix(ascloudpath): incorporates buckets

cloudfiles/secrets.py
Resolves #26
Allows CF to operate in a read-only environment.
=> fix(secrets): don't create empty directories

README.md, cloudfiles/compression.py, requirements.txt, setup.py
This significantly improves certain workloads such as unsharded segmentation. 
https://github.com/dcwatson/deflate/pull/3
=> perf: use libdeflate to improve gzip decompression

ChangeLog, LICENSE, README.md, cli.py, cloudfiles/cloudfiles.py, cloudfiles/lib.py, cloudfiles/paths.py, requirements.txt, setup.py
The `cloudfiles` CLI command is now automatically installed with cloud-files.
=> feat(cli): added cp, ls, and license commands

cloudfiles/cloudfiles.py, cloudfiles/interfaces.py, cloudfiles_cli/cloudfiles_cli.py
feat(interfaces): add head command
=> feat(cli): add head command

README.md, cloudfiles/cloudfiles.py
Allows for the efficient use of multi-core.
=> feat: parallel flag for get, puts, put_jsons, delete

cloudfiles/cloudfiles.py, cloudfiles/interfaces.py
=> feat: allow user to specify storage_class for cloud uploads

README.md, cloudfiles/cloudfiles.py, cloudfiles/connectionpools.py, cloudfiles/interfaces.py
=> feat(requester pays): GCS and S3

automated_test.py, cloudfiles/cloudfiles.py
Raises errors immediately for `cf.get`.
=> BREAKING: feat(get): add raise_errors flag enabled by default

cloudfiles_cli/cloudfiles_cli.py
```
cloudfiles cp $PATHS -
```
Will output to stdout.
=> feat(cli): adds stdout to cp

automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/lib.py, cloudfiles/paths.py, cloudfiles_cli/cloudfiles_cli.py
=> redesign: make cp -r work more like ordinary cp

automated_test.py, cloudfiles_cli/cloudfiles_cli.py
=> fix: rm -r test could delete test and test2

cloudfiles/interfaces.py
Special logic for this domain in the https module.
=> feat: support listing on https://storage.googleapis.com/

cloudfiles/cloudfiles.py, cloudfiles/paths.py
Also make asfilepath automatically parse strings
=> feat: add cf.join for joining file paths

cloudfiles/cloudfiles.py, cloudfiles/interfaces.py, cloudfiles_cli/cloudfiles_cli.py
- Adds ability to do multipart validation for s3 for the `cloudfiles verify` command.
- Fixes bug when using RANGE requests on TigerData
- Normalizes windows paths to posix for comparisons.
=> feat: multipart validation

cloudfiles/cloudfiles.py, cloudfiles/interfaces.py
Allow file handles and files larger than 100MB to use multi-part upload.
=> feat: multi-part s3 upload support

cloudfiles/interfaces.py
Matching the behavior of other interfaces
=> Add kwargs to S3Interface

cloudfiles/cloudfiles.py, cloudfiles/connectionpools.py, cloudfiles/interfaces.py, cloudfiles_cli/cloudfiles_cli.py
=> feat: add no_sign_request for s3 services

automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/interfaces.py, cloudfiles/paths.py, cloudfiles/secrets.py
Adding support for CAVE via middleauth+https
=> feat: add middleauth+https paths indicate CAVE interface
