cloudfiles/lib.py, requirements.txt, setup.cfg
I was trying to avoid a numpy dependency, but that function is very
useful for everyone that is currently using CloudFiles. I considered
using a try except for ImportError, but that would have been confusing
for people used to seamless operation with numpy types.
Resolves #4
=> fix: import error for numpy in JSON decoder

automated_test.py, cloudfiles/cloudfiles.py
redesign: use 'compress' instead of 'encoding' to ensure get/put compatibility
=> perf: skip compress/decompress cycle during transfers

README.md, automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/compression.py
```python
cloudfiles/compression.py
def transcode(
files, encoding, level=None, 
progress=False, in_place=False
):
"""
Given the output of get, which may include raw files, 
transcode the compresson scheme into the one specified by 
encoding. If the files are raw and the schemes match, 
the decompression-compression cycle will be skipped.
level: input of compression level e.g. 6 for gzip
progress: show a progress bar
in_place: modify the files in-place to save memory
Yields: {
'path': ,
'content': ,
'compress': ,
'raw': ,
}
```
=> feat: add transcode to compression

automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/exceptions.py, cloudfiles/interfaces.py, cloudfiles/lib.py
A small download test seemed to show no significant adverse performance impact from this computation.
One important ease-of-use consideration is how to process strings that are ingested. Do we require strict binary input to CloudFiles or can we assume strings are utf8? If strings are not utf8 a simple remedy for the end user is to encode their strings to binary before sending it into CF. However, python27 is more tricky as strings and bytes are the same so not as easily detected. We could simply disable this check for py27 or drop support.
Should we allow disabling the md5 checks? If a problem with them develops it might make it easier for users to work around those problems.
=> feat: perform md5 integrity checks

cloudfiles/interfaces.py, requirements.txt
The new release of `google-cloud-storage==1.31.1` has the fixes in it for parsing the MD5 correctly.
=> feat: reenable md5 for GCS

requirements.txt, setup.py
As of 0.2.0, three issues with deflate were fixed:
- Memory leak
- -fPIC for src instsall
- Binaries released for major platforms
Thanks @dcwatson!
=> chore: upgrade deflate to a standard install

automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/scheduler.py, setup.cfg
feat: allow passing progress as a tqdm instance
refactor: use comute_url for more tests
If using get_json you lose the path information per file so you can't sort them if you need to, so the sorting needs to happen automatically.
=> fix: preserve order for get_json

cloudfiles/cloudfiles.py, requirements.txt
Using cf.get with parallel on MacOS was causing segfaults due to the non-forksafe behavior of grand central dispatch when it searches for proxy servers. We disable proxies on Mac to avoid this issues when using parallel.
Our restrictions on urllib3 have become outdated as is its download of brotlipy (no obsolete).
=> fix: segfault on MacOS parallel & dependency issues

ChangeLog, cloudfiles/interfaces.py, cloudfiles/lib.py
We used the following documents as a guide:
- https://teppen.io/2018/10/23/aws_s3_verify_etags/
- https://teppen.io/2018/06/23/aws_s3_etags/
Gracious thank you to the authors of those articles for the code and advice.
The PR here is a bit different. As the S3 logic is particular to Amazon, it was not possible to do this in the common logic. This means the multipart code will retry while other md5 failures will not. However, should they all be retrying?
Resolves #49
=> feat: enable md5 validation for multipart s3 downloads

cloudfiles/cloudfiles.py, cloudfiles/interfaces.py
`cloudfiles cp -r path matrix://bucket/` was copying stuff like:
`bucket/C:\\path\\file\\`
This was because the path sep was not being considered in the file interface listing operator and we were not converting from Windows to posix during transfers.
=> fix: transfer paths from windows correctly

cloudfiles/interfaces.py
S3 was checking full Etag md5 for range requests.
=> fix: range requests blocked by ETag check on S3

cloudfiles/cloudfiles.py, cloudfiles/lib.py, cloudfiles_cli/cloudfiles_cli.py
Tool to help check if transfers completed successfully.
Compare two directories list of files to see if the content length matches, then ETag, then Content-Md5. Performs comparison based on matching filenames. By default, returns an error if the directories don't match, but you can also force it to do a comparison of the intersection of the two directories.
Example:
```
cloudfiles verify gs://bucket/files s3://bucket/files --verbose
```
The filesystem doesn't store ETags or md5 hashes, so we add an option to compute it on the fly:
```
cloudfiles verify ./mydata gs://bucket/copy-of-my-data/ --md5
```
CloudFiles checks md5 during downloads and uploads, but this feature gives users more confidence when they can see everything matches.
=> feat(cli): adds verify command 

README.md, automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/connectionpools.py, cloudfiles/interfaces.py, cloudfiles/paths.py, cloudfiles_cli/cloudfiles_cli.py
This allows us to soft(er)-code `matrix://` and `tigerdata://` but also allows end-users to add their own aliases dynamically.
Persistent aliases can be added, listed, and removed via the command line which will be saved in ~/.cloudfiles/aliases.json. The file will only be accessed once (per process) if an unknown protocol is encountered.
=> feat: s3 aliases

cloudfiles/interfaces.py
Connections were opened using aliases, such as `matrix`, but release_connection looked for `s3`. This should reduce the number of open connections at least to pre-alias levels.
=> fix(S3Interface): release_connection respects alias

README.md, automated_test.py, cloudfiles/__init__.py, cloudfiles/resumable_tools.py, cloudfiles_cli/cloudfiles_cli.py
Resolves #80 
Adds `ResumableTransfer` class and `cloudfiles xfer` CLI subgroup.
The transfer works by first loading a sqlite database with filenames, a "done" flag, and a lease time. Then, clients can attach to the database and execute the transfer in batches. When multiple clients are used, a lease time must be set so that the database does not return the same set of files to each client (and is robust).
To use with a single client:
```python
from cloudfiles import ResumableTransfer
rt = ResumableTransfer("DATABASE_NAME.db") # doesn't have to exist 
rt.init(SOURCE_PATH, DEST_PATH, [ENCODING])
rt.execute(progress=True)
rt.close() # deletes database
```
```bash
cloudfiles xfer init SOURCE DEST --db DATABASE_NAME.db
cloudfiles xfer execute DATABASE_NAME.db
```
For use with multiple …
=> feat: resumable transfers

cloudfiles/cloudfiles.py, cloudfiles/gcs.py, cloudfiles/interfaces.py, cloudfiles/lib.py, cloudfiles/typing.py, cloudfiles_cli/cloudfiles_cli.py
Transparently handles large uploads (>=100MB) on GCS by using the composite upload feature. This splits uploads into 100MB parts and then merges them 32 parts at a time recursively. The smaller part files are deleted.
Part format: `filename.{depth}.{partno}.part`
A few other goodies are added here:
- Faster local file transfers
- FileInterface also accepts a file handle
- Fixes broken transcoding for single files on CLI
- Transfers of compressed files from GCS to local fs will get a compression suffix
=> feat: support for GCS composite uploads

README.md, automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/connectionpools.py, cloudfiles/interfaces.py, cloudfiles/paths.py, cloudfiles/scheduler.py, cloudfiles_cli/__init__.py, cloudfiles_cli/cloudfiles_cli.py
- More comprehensive testing of transfer_to/transfer_from
- Fixes for `mem://` protocol (parsing, buckets)
- File-to-file transfers handle compression
- Low memory transfer to gs, s3 by using file handles from local disk
- gs->gs and s3->s3 copies no longer require download/upload from client
- Support for renaming files during transfer
- Use the main thread for single element jobs
- Removes monkey patch from CLI as this causes problems with boto's advanced functions which use threads under the hood
- CloudFiles automatically decides whether to use threads or green threads depending on the monkey patch state (you can still force it to use one or the other)
=> perf: better memory usage for file to gs/s3 transfer

AUTHORS, ChangeLog, automated_test.py, cloudfiles/interfaces.py
Allows token type secrets to be fed in. 
Also makes retry abort quickly for requests.exceptions.HTTPError
=> fix: ensure http secrets is compatible with graphene tokens

cloudfiles/cloudfiles.py, cloudfiles/interfaces.py, cloudfiles/secrets.py, requirements.txt
This mainly helps when using multiple cloud-volume instance with local cache, without locking the cache maybe read when incomplete. Use fastener to put a shared lock when reading files and an exclusive lock when writing files.
The patch creates a `xxx.lock` file when cloud-files try to access file `xxx`, in the same folder. If it does not have write permit, fallback to the no lock path, though I am not sure if it make sense to still try put files in that case. I did not try cleanup the files, since it is tricky to find out when all the locks are resolved. An alternative approach is to create lock files somewhere else, maybe some folder under `CLOUD_FILES_DIR`
Only tested the patch under linux.
=> Use fasteners to lock local files

cloudfiles/interfaces.py
Google storage client has [md5 chucksum enabled by default](https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/blob.py#L1348-L1356). Since CloudFiles does checksum validation itself, we should disable checksum in the `download_as_bytes` call. This reduces overall time from 5s to 4s, when downloading 31 files, 10-20M each.
For some reason it seems if I disable checksum validation in CloudFiles instead, there is no speed improvement.
=> Disable internal checksum validation in GCS client

automated_test.py, cloudfiles/connectionpools.py, cloudfiles/secrets.py
This PR adds support for `AWS_SESSION_TOKEN` so that users can use an AWS account that supports this when using CloudFiles. Previously, requests would all return `Forbidden` because the session token was not actually being used during boto3 client creation. The PR adds support for `AWS_SESSION_TOKEN` to be used in an environment variable as well as through `aws-secret.json`. Fixes #101 .
=> Add support for AWS_SESSION_TOKEN

cloudfiles/interfaces.py, cloudfiles/lib.py
AWS recently changed their file upload validation procedure and seem to be ignoring ContentMD5 and instead are applying their own algorithm. This causes ",aws-chunked" to get appended to the Content-Encoding field which causes havoc.
We circumvent this behavior in this PR by calculating the crc32c and specifying it as the chosen algorithm up front.
This is probably a net benefit, since crc32c can be computed at 100 GB/sec these days (though this implementation is probably only ~1 GB/sec).
=> fix: prevent aws-chunked from populating in Content-Encoding

automated_test.py, cloudfiles/paths.py
CloudFiles path parsing now supports e.g. gs://bucket/path/|zarr2: in addition to zarr2://gs://bucket/path/
=> fix: support |format: style of cloudpaths

cloudfiles_cli/cloudfiles_cli.py
This changes the instruction to multiprocessing to use "spawn" seemingly correctly. So far in my testing, the bug where high process counts causes freezing disappears.
Thanks ChatGPT for the correct invocation.
=> fix: try different multi-processing method

cloudfiles/interfaces.py, cloudfiles/secrets.py
Accept `secrets={'token': ... }` as well as `SERVER-cave-secret.json` files.
=> fix(cave): expanded credentials methods

.github/workflows/test-suite.yml, README.md, automated_test.py, cloudfiles/cloudfiles.py, cloudfiles/interfaces.py, cloudfiles/monitoring.py, cloudfiles_cli/cloudfiles_cli.py, requirements.txt, setup.cfg
This PR adds estimated and global measurements for upload and download speed and provides a matplotlib based chart for different capabilities.
In the CLI, this adds:
- `--flight-time` which shows a gantt chart of the flight time of different files colored by file size.
- `--machine-io-rate` samples the OS network counters to measure the total network IO on the machine
- `--machine-io-rate-buffer-sec` sets the size of the circular buffer in seconds, the sampling interval is 0.25 seconds.
- `--io-rate` estimates the IO contribution from file flight times. This is useful when CloudFiles is not the only network traffic on the machine. You can use the two measurements to figure out the relative contribution of different processes.
This PR also introduces two new objects:
- …
=> feat: performance monitoring
